services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: log-ai-postgres
    restart: always
    environment:
      POSTGRES_USER: logai
      POSTGRES_PASSWORD: logai1234
      POSTGRES_DB: log_ai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

# PS D:\dev\study\ops-log-ai-assistant> docker compose up -d
# [+] up 21/21
#  ✔ Image pgvector/pgvector:pg16              Pulled                                                                           31.3s
#  ✔ Network ops-log-ai-assistant_default      Created                                                                           0.1s
#  ✔ Volume ops-log-ai-assistant_postgres_data Created                                                                           0.0s
#  ✔ Container log-ai-postgres                 Started                                                                           1.0s

# What's next:
#     Filter, search, and stream logs from all your Compose services
#     in one place with Docker Desktop's Logs view. docker-desktop://dashboard/logs